### ISSUE TITLE
CoreProtect无法工作

### ISSUE THREAD

**Issue by nainiu233** [CatServer/CatServer#12]
[16:33:49] [Server thread/INFO]: nainiu issued server command: /co i
[16:33:49] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'co' in plugin CoreProtect v2.15.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[PluginCommand.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[SimpleCommandMap.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:702) ~[CraftServer.class:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1591) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1436) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
        at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:843) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:780) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by nainiu233** [comment]
[20:49:36] [Server thread/INFO]: [CoreProtect] Enabling CoreProtect v2.15.0
[20:49:36] [Server thread/INFO]: [CoreProtect] Spigot 1.13 or higher is required.
[20:49:36] [Server thread/INFO]: [CoreProtect] CoreProtect was unable to start.
[20:49:36] [Server thread/INFO]: [CoreProtect] Disabling CoreProtect v2.15.0

**Comment by megoesrawr** [comment]
This is a 1.12.2 spigot/forge project, not 1.13

**Comment by bigenergy** [comment]
CoreProtect can log blocks from mods on CatServer?

**Comment by nainiu233** [comment]
是我搞错了 抱歉 请关闭它
