### ISSUE TITLE
custom plugin issues

### ISSUE THREAD

**Issue by noy98** [CatServer/CatServer#22]
`org.bukkit.command.CommandException: Unhandled exception executing command '금고' in plugin SafeChest v1.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[SimpleCommandMap.class:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:700) ~[CraftServer.class:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1591) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1436) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:842) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:779) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: javafx/util/Pair
	at milkyway.CommandModule.Factory.ModuleFactory.createCommandData(ModuleFactory.java:12) ~[?:?]
	at milkyway.CommandModule.Data.CommandModule.executeCommand(CommandModule.java:30) ~[?:?]
	at milkyway.CommandModule.Data.CommandModule.onCommand(CommandModule.java:87) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-Spigot-dcd1643-e60fc34]
	... 15 more`

when I execute command, they have an error like this.
What is this problem? and How to solve?

**Comment by IceSoulHanxi** [comment]
Hmmmm This error message says that you are missing javafx, you need to add it to the classpath yourself.

**Comment by IceSoulHanxi** [comment]
https://stackoverflow.com/questions/25329886/javafx-noclassdeffounderror
