### ISSUE TITLE
加入CubicChunks后服务器崩溃

### ISSUE THREAD

**Issue by zhuyifan0716** [CatServer/CatServer#25]
原版+forge-1.12.2-14.23.5.2768下可以成功运行
在最新版catserver中latest.log报如下错误

[22:05:14] [main/INFO] [LaunchWrapper]: Loading tweak class name catserver.server.launcher.CatServerTweaker
[22:05:14] [main/INFO] [LaunchWrapper]: Using primary tweak class name catserver.server.launcher.CatServerTweaker
[22:05:14] [main/INFO] [LaunchWrapper]: Calling tweak class catserver.server.launcher.CatServerTweaker
[22:05:14] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2815 for Minecraft 1.12.2 loading
[22:05:14] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_201, running on Windows 10:amd64:10.0, installed at E:\Program Files (x86)\Java\jdk1.8.0_201\jre
[22:05:14] [main/ERROR] [FML]: Apache Maven library folder was not in the format expected. Using default libraries directory.
[22:05:14] [main/ERROR] [FML]: Full: D:\catserver\libraries\maven-artifact-3.5.3.jar
[22:05:14] [main/ERROR] [FML]: Trimmed: d:/catserver/
[22:05:14] [main/INFO] [FML]: Searching D:\catserver\.\mods for mods
[22:05:14] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar
[22:05:14] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:05:14] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[22:05:14] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.5 Source=file:/D:/catserver/./mods/CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar Service=LaunchWrapper Env=SERVER
[22:05:15] [main/WARN] [FML]: The coremod CubicChunksCoreMod (io.github.opencubicchunks.cubicchunks.core.asm.coremod.CubicChunksCoreMod) is not signed!
[22:05:15] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[22:05:15] [main/INFO] [mixin]: Adding new token provider io.github.opencubicchunks.cubicchunks.core.asm.coremod.CubicChunksCoreMod$TokenProvider to MixinEnvironment[DEFAULT]
[22:05:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[22:05:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:05:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:05:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:05:16] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[22:05:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:05:16] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[22:05:16] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@1db0ec27
[22:05:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[22:05:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[22:05:16] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[22:05:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[22:05:16] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[22:05:16] [main/INFO] [CubicChunksMixinConfig]: No Optifine detected
[22:05:16] [main/INFO] [CubicChunksMixinConfig]: BetterFps is NOT installed. Will not enable FastBeacon mixin.
[22:05:16] [main/INFO] [CubicChunksMixinConfig]: Loading configuration file D:\catserver\.\config\cubicchunks_mixin_config.json
[22:05:16] [main/ERROR] [mixin]: Critical injection failure: LVT in net/minecraft/server/MinecraftServer::func_71247_a(Ljava/lang/String;Ljava/lang/String;JLnet/minecraft/world/WorldType;Ljava/lang/String;)V has incompatible changes at opcode 45 in callback net/minecraft/server/MinecraftServer::handler$onWorldSettingsCreate$zzi000.
Expected: [Lnet/minecraft/world/storage/ISaveHandler;, Lnet/minecraft/world/storage/WorldInfo;, Lnet/minecraft/world/WorldSettings;]
   Found: [Lnet/minecraft/world/WorldSettings;]
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/server/MinecraftServer::func_71247_a(Ljava/lang/String;Ljava/lang/String;JLnet/minecraft/world/WorldType;Ljava/lang/String;)V has incompatible changes at opcode 45 in callback net/minecraft/server/MinecraftServer::handler$onWorldSettingsCreate$zzi000.
Expected: [Lnet/minecraft/world/storage/ISaveHandler;, Lnet/minecraft/world/storage/WorldInfo;, Lnet/minecraft/world/WorldSettings;]
   Found: [Lnet/minecraft/world/WorldSettings;]
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:475)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:425)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:199)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:267)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1198)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:909)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:309)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.Class.forName0(Native Method)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.Class.forName(Class.java:348)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at catserver.server.launcher.CatServerLauncher.run(CatServerLauncher.java:72)
[22:05:16] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at catserver.server.launcher.CatServerLauncher.main(CatServerLauncher.java:19)
[22:05:16] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.server.MinecraftServer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at catserver.server.launcher.CatServerLauncher.run(CatServerLauncher.java:72) [MCX.jar:git-97e64db-Community]
	at catserver.server.launcher.CatServerLauncher.main(CatServerLauncher.java:19) [MCX.jar:git-97e64db-Community]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/server/MinecraftServer::func_71247_a(Ljava/lang/String;Ljava/lang/String;JLnet/minecraft/world/WorldType;Ljava/lang/String;)V has incompatible changes at opcode 45 in callback net/minecraft/server/MinecraftServer::handler$onWorldSettingsCreate$zzi000.
Expected: [Lnet/minecraft/world/storage/ISaveHandler;, Lnet/minecraft/world/storage/WorldInfo;, Lnet/minecraft/world/WorldSettings;]
   Found: [Lnet/minecraft/world/WorldSettings;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:475) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:425) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:199) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:267) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1198) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:909) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:309) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 12 more
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:main:19]: java.lang.reflect.InvocationTargetException
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:main:19]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:main:19]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:main:19]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:main:19]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:main:19]: 	at catserver.server.launcher.CatServerLauncher.run(CatServerLauncher.java:72)
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:main:19]: 	at catserver.server.launcher.CatServerLauncher.main(CatServerLauncher.java:19)
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:run:81]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:run:81]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:run:81]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:run:81]: 	at java.lang.Runtime.exit(Runtime.java:107)
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:run:81]: 	at java.lang.System.exit(System.java:971)
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:run:81]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:run:81]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:05:16] [main/INFO] [STDERR]: [catserver.server.launcher.CatServerLauncher:run:81]: 	... 6 more
[22:05:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[22:05:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[22:05:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[22:05:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[22:05:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[22:05:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at catserver.server.launcher.CatServerLauncher.run(CatServerLauncher.java:82)
[22:05:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at catserver.server.launcher.CatServerLauncher.main(CatServerLauncher.java:19)

**Comment by IceSoulHanxi** [comment]
这个Mod会对区块进行扩展，导致Bukkit和其他mod无法正常使用，所以说暂时不做兼容
