### ISSUE TITLE
加了AppleCore无法启动

### ISSUE THREAD

**Issue by molehzy** [CatServer/CatServer#4]
[02:34:10] [main/INFO] [LaunchWrapper]: Loading tweak class name catserver.server.launcher.CatServerTweaker
[02:34:10] [main/INFO] [LaunchWrapper]: Using primary tweak class name catserver.server.launcher.CatServerTweaker
[02:34:10] [main/INFO] [LaunchWrapper]: Calling tweak class catserver.server.launcher.CatServerTweaker
[02:34:11] [main/DEBUG] [FML]: Injecting tracing printstreams for STDOUT/STDERR.
[02:34:11] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2808 for Minecraft 1.12.2 loading
[02:34:11] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_192, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_192
[02:34:11] [main/DEBUG] [FML]: Java classpath at launch is:
[02:34:11] [main/DEBUG] [FML]:     CatServer-git-917005d-Community.jar
[02:34:11] [main/DEBUG] [FML]: Java library path at launch is:
[02:34:11] [main/DEBUG] [FML]:     C:\Program Files (x86)\Common Files\Oracle\Java\javapath
[02:34:11] [main/DEBUG] [FML]:     C:\Windows\Sun\Java\bin
[02:34:11] [main/DEBUG] [FML]:     C:\Windows\system32
[02:34:11] [main/DEBUG] [FML]:     C:\Windows
[02:34:11] [main/DEBUG] [FML]:     C:\Program Files\cmder_mini\bin
[02:34:11] [main/DEBUG] [FML]:     C:\Program Files\cmder_mini\vendor\conemu-maximus5\ConEmu\Scripts
[02:34:11] [main/DEBUG] [FML]:     C:\Program Files\cmder_mini\vendor\conemu-maximus5
[02:34:11] [main/DEBUG] [FML]:     C:\Program Files\cmder_mini\vendor\conemu-maximus5\ConEmu
[02:34:11] [main/DEBUG] [FML]:     C:\Program Files (x86)\Common Files\Oracle\Java\javapath
[02:34:11] [main/DEBUG] [FML]:     C:\Windows\system32
[02:34:11] [main/DEBUG] [FML]:     C:\Windows
[02:34:11] [main/DEBUG] [FML]:     C:\Windows\System32\Wbem
[02:34:11] [main/DEBUG] [FML]:     C:\Windows\System32\WindowsPowerShell\v1.0\
[02:34:11] [main/DEBUG] [FML]:     C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
[02:34:11] [main/DEBUG] [FML]:     C:\Program Files (x86)\ZeroTier\One\
[02:34:11] [main/DEBUG] [FML]:     C:\Program Files\cmder_mini
[02:34:11] [main/DEBUG] [FML]:     C:\Program Files\cmder_mini\
[02:34:11] [main/DEBUG] [FML]:     .
[02:34:12] [main/ERROR] [FML]: Apache Maven library folder was not in the format expected. Using default libraries directory.
[02:34:12] [main/ERROR] [FML]: Full: C:\360Download\CatServer-master\libraries\maven-artifact-3.5.3.jar
[02:34:12] [main/ERROR] [FML]: Trimmed: c:/360download/catserver-master/
[02:34:12] [main/DEBUG] [FML]: Determined Minecraft Libraries Root: .\libraries
[02:34:12] [main/DEBUG] [FML]: Cleaning up mods folder: .\mods
[02:34:12] [main/DEBUG] [FML]: Examining file: AppleCore-mc1.12.2-3.1.4.jar
[02:34:12] [main/DEBUG] [FML]: Enabling runtime deobfuscation
[02:34:12] [main/DEBUG] [FML]: Instantiating coremod class FMLCorePlugin
[02:34:12] [main/DEBUG] [FML]: Found signing certificates for coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin)
[02:34:12] [main/DEBUG] [FML]: Found certificate e3c3d50c7c986df74c645c0ac54639741c90a557
[02:34:12] [main/DEBUG] [FML]: Added access transformer class net.minecraftforge.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[02:34:12] [main/DEBUG] [FML]: Enqueued coremod FMLCorePlugin
[02:34:12] [main/DEBUG] [FML]: Instantiating coremod class FMLForgePlugin
[02:34:12] [main/DEBUG] [FML]: Found signing certificates for coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin)
[02:34:12] [main/DEBUG] [FML]: Found certificate e3c3d50c7c986df74c645c0ac54639741c90a557
[02:34:12] [main/DEBUG] [FML]: Enqueued coremod FMLForgePlugin
[02:34:12] [main/DEBUG] [FML]: All fundamental core mods are successfully located
[02:34:12] [main/DEBUG] [FML]: Discovering coremods
[02:34:12] [main/INFO] [FML]: Searching C:\360Download\CatServer-master\.\mods for mods
[02:34:12] [main/DEBUG] [FML]:   Adding AppleCore-mc1.12.2-3.1.4.jar to the mod list
[02:34:12] [main/DEBUG] [FML]: Examining for coremod candidacy AppleCore-mc1.12.2-3.1.4.jar
[02:34:12] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.1.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:34:12] [main/DEBUG] [FML]: Instantiating coremod class AppleCore
[02:34:12] [main/DEBUG] [FML]: The coremod squeek.applecore.AppleCore requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[02:34:12] [main/WARN] [FML]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[02:34:12] [main/DEBUG] [FML]: Enqueued coremod AppleCore
[02:34:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[02:34:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[02:34:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[02:34:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[02:34:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[02:34:12] [main/DEBUG] [FML]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[02:34:12] [main/DEBUG] [FML]: Injection complete
[02:34:12] [main/DEBUG] [FML]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[02:34:12] [main/DEBUG] [FML]: Running coremod plugin FMLCorePlugin
[02:34:14] [main/DEBUG] [FML]: Read 1943 binary patches
[02:34:14] [main/DEBUG] [FML]: Loading deobfuscation resource /deobfuscation_data-1.12.2.lzma with 36083 records
[02:34:14] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[02:34:14] [main/DEBUG] [FML]: Coremod plugin class FMLCorePlugin run successfully
[02:34:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[02:34:14] [main/DEBUG] [FML]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[02:34:14] [main/DEBUG] [FML]: Injection complete
[02:34:14] [main/DEBUG] [FML]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[02:34:14] [main/DEBUG] [FML]: Running coremod plugin FMLForgePlugin
[02:34:14] [main/DEBUG] [FML]: Coremod plugin class FMLForgePlugin run successfully
[02:34:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[02:34:14] [main/DEBUG] [FML]: Loaded 214 rules from AccessTransformer config file forge_at.cfg
[02:34:14] [main/DEBUG] [FML]: Validating minecraft
[02:34:15] [main/DEBUG] [FML]: Minecraft validated, launching...
[02:34:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[02:34:15] [main/DEBUG] [FML]: Injecting coremod AppleCore \{squeek.applecore.AppleCore\} class transformers
[02:34:15] [main/DEBUG] [FML]: Injection complete
[02:34:15] [main/DEBUG] [FML]: Running coremod plugin for AppleCore \{squeek.applecore.AppleCore\}
[02:34:15] [main/DEBUG] [FML]: Running coremod plugin AppleCore
[02:34:15] [main/DEBUG] [FML]: Coremod plugin class AppleCore run successfully
[02:34:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[02:34:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[02:34:16] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[02:34:18] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
	at catserver.server.launcher.CatServerLaunchWrapper.run(CatServerLaunchWrapper.java:64) [CatServer-git-917005d-Community.jar:git-917005d-Personal]
	at catserver.server.launcher.CatServerLaunchWrapper.main(CatServerLaunchWrapper.java:18) [CatServer-git-917005d-Community.jar:git-917005d-Personal]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockCake
	at net.minecraft.block.Block.func_149671_p(Block.java:2429) ~[aow.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:777) ~[ni.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1643) ~[MinecraftServer.class:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockCake
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_192]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_192]
	at net.minecraft.block.Block.func_149671_p(Block.java:2429) ~[aow.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:777) ~[ni.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1643) ~[MinecraftServer.class:?]
	... 12 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer squeek.applecore.asm.TransformerModuleHandler@1235151c from coremod AppleCore
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[forge-1.12.2-14.23.5.2808-universal.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_192]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_192]
	at net.minecraft.block.Block.func_149671_p(Block.java:2429) ~[aow.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:777) ~[ni.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1643) ~[MinecraftServer.class:?]
	... 12 more
Caused by: java.lang.RuntimeException: Could not replace FoodStats.addStats call in net/minecraft/block/BlockCake.func_180682_b
   L0
    LINENUMBER 68 L0
    ALOAD 4
    ICONST_0
    INVOKEVIRTUAL net/minecraft/entity/player/EntityPlayer.func_71043_e (Z)Z
    IFNE L1
   L2
    LINENUMBER 70 L2
    ICONST_0
    IRETURN
   L1
    LINENUMBER 74 L1
   FRAME SAME
    ALOAD 4
    GETSTATIC net/minecraft/stats/StatList.field_188076_J : Lnet/minecraft/stats/StatBase;
    INVOKEVIRTUAL net/minecraft/entity/player/EntityPlayer.func_71029_a (Lnet/minecraft/stats/StatBase;)V
   L3
    LINENUMBER 76 L3
    ALOAD 4
    INVOKEVIRTUAL net/minecraft/entity/player/EntityPlayer.func_71024_bL ()Lnet/minecraft/util/FoodStats;
    GETFIELD net/minecraft/util/FoodStats.field_75127_a : I
    ISTORE 5
   L4
    LINENUMBER 78 L4
    ALOAD 4
    ICONST_2
    ILOAD 5
    IADD
    INVOKESTATIC org/bukkit/craftbukkit/v1_12_R1/event/CraftEventFactory.callFoodLevelChangeEvent (Lnet/minecraft/entity/player/EntityPlayer;I)Lorg/bukkit/event/entity/FoodLevelChangeEvent;
    ASTORE 6
   L5
    LINENUMBER 80 L5
    ALOAD 6
    INVOKEVIRTUAL org/bukkit/event/entity/FoodLevelChangeEvent.isCancelled ()Z
    IFNE L6
   L7
    LINENUMBER 81 L7
    ALOAD 4
    INVOKEVIRTUAL net/minecraft/entity/player/EntityPlayer.func_71024_bL ()Lnet/minecraft/util/FoodStats;
    ALOAD 6
    INVOKEVIRTUAL org/bukkit/event/entity/FoodLevelChangeEvent.getFoodLevel ()I
    ILOAD 5
    ISUB
    LDC 0.1
    INVOKEVIRTUAL net/minecraft/util/FoodStats.func_75122_a (IF)V
   L6
    LINENUMBER 84 L6
   FRAME APPEND [I org/bukkit/event/entity/FoodLevelChangeEvent]
    ALOAD 4
    CHECKCAST net/minecraft/entity/player/EntityPlayerMP
    INVOKEVIRTUAL net/minecraft/entity/player/EntityPlayerMP.getBukkitEntity ()Lorg/bukkit/craftbukkit/v1_12_R1/entity/CraftPlayer;
    INVOKEVIRTUAL org/bukkit/craftbukkit/v1_12_R1/entity/CraftPlayer.sendHealthUpdate ()V
   L8
    LINENUMBER 85 L8
    ALOAD 3
    GETSTATIC net/minecraft/block/BlockCake.field_176589_a : Lnet/minecraft/block/properties/PropertyInteger;
    INVOKEINTERFACE net/minecraft/block/state/IBlockState.func_177229_b (Lnet/minecraft/block/properties/IProperty;)Ljava/lang/Comparable;
    CHECKCAST java/lang/Integer
    INVOKEVIRTUAL java/lang/Integer.intValue ()I
    ISTORE 7
   L9
    LINENUMBER 87 L9
    ILOAD 7
    BIPUSH 6
    IF_ICMPGE L10
   L11
    LINENUMBER 89 L11
    ALOAD 1
    ALOAD 2
    ALOAD 3
    GETSTATIC net/minecraft/block/BlockCake.field_176589_a : Lnet/minecraft/block/properties/PropertyInteger;
    ILOAD 7
    ICONST_1
    IADD
    INVOKESTATIC java/lang/Integer.valueOf (I)Ljava/lang/Integer;
    INVOKEINTERFACE net/minecraft/block/state/IBlockState.func_177226_a (Lnet/minecraft/block/properties/IProperty;Ljava/lang/Comparable;)Lnet/minecraft/block/state/IBlockState;
    ICONST_3
    INVOKEVIRTUAL net/minecraft/world/World.func_180501_a (Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;I)Z
    POP
    GOTO L12
   L10
    LINENUMBER 93 L10
   FRAME APPEND [I]
    ALOAD 1
    ALOAD 2
    INVOKEVIRTUAL net/minecraft/world/World.func_175698_g (Lnet/minecraft/util/math/BlockPos;)Z
    POP
   L12
    LINENUMBER 96 L12
   FRAME SAME
    ICONST_1
    IRETURN
   L13
    LOCALVARIABLE oldFoodLevel I L4 L13 5
    LOCALVARIABLE event Lorg/bukkit/event/entity/FoodLevelChangeEvent; L5 L13 6
    LOCALVARIABLE i I L9 L13 7
    LOCALVARIABLE this Lnet/minecraft/block/BlockCake; L0 L13 0
    LOCALVARIABLE worldIn Lnet/minecraft/world/World; L0 L13 1
    LOCALVARIABLE pos Lnet/minecraft/util/math/BlockPos; L0 L13 2
    LOCALVARIABLE state Lnet/minecraft/block/state/IBlockState; L0 L13 3
    LOCALVARIABLE player Lnet/minecraft/entity/player/EntityPlayer; L0 L13 4
    MAXSTACK = 6
    MAXLOCALS = 8

	at squeek.applecore.asm.module.ModuleBlockFood.addOnBlockFoodEatenHook(ModuleBlockFood.java:96) ~[AppleCore-mc1.12.2-3.1.4.jar:?]
	at squeek.applecore.asm.module.ModuleBlockFood.transform(ModuleBlockFood.java:36) ~[AppleCore-mc1.12.2-3.1.4.jar:?]
	at squeek.applecore.asm.TransformerModuleHandler.transform(TransformerModuleHandler.java:41) ~[AppleCore-mc1.12.2-3.1.4.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge-1.12.2-14.23.5.2808-universal.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_192]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_192]
	at net.minecraft.block.Block.func_149671_p(Block.java:2429) ~[aow.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:777) ~[ni.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1643) ~[MinecraftServer.class:?]
	... 12 more

**Comment by IceSoulHanxi** [comment]
AppleCore通过ASM修改了某些代码导致与服务端冲突, 请加群下载Cat专用版AppleCore

**Comment by CatServer** [comment]
服务端已经修复该兼容问题
