### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by mulukou** [CatServer/CatServer#43]
Server starts without any mods, when I put the mods (which are working on a Forge server) it crashes on the start

[11:35:58] [CatServer Launch/INFO]: Loading libraries, please wait...
[11:35:58] [CatServer Launch/INFO]: Loading libraries, please wait...
Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
Transforming net.minecraft.block.Block Finished.
[11:36:00] [CatServer Launch/ERROR]: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at catserver.server.launcher.CatServerLauncher.run(CatServerLauncher.java:61)
	at catserver.server.launcher.CatServerLauncher.main(CatServerLauncher.java:27)
Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:971)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more

[11:36:00] [CatServer Launch/ERROR]: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at catserver.server.launcher.CatServerLauncher.run(CatServerLauncher.java:61)
	at catserver.server.launcher.CatServerLauncher.main(CatServerLauncher.java:27)
Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:971)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more

[11:36:00] [CatServer Launch/ERROR]: A problem occurred running the Server launcher.
[11:36:00] [CatServer Launch/ERROR]: A problem occurred running the Server launcher.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at catserver.server.launcher.CatServerLauncher.run(CatServerLauncher.java:61)
	at catserver.server.launcher.CatServerLauncher.main(CatServerLauncher.java:27)
Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:971)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more
Exception in thread "main" net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:971)
	at catserver.server.launcher.CatServerLauncher.run(CatServerLauncher.java:67)
	at catserver.server.launcher.CatServerLauncher.main(CatServerLauncher.java:27)

Mod List:

- bspkrCore
- TreeCapitator
- Actually Additions
- Aether II
- Akashic Tome
- albedo
- AppleSkin
- Applied Energistics 2
- AutoRegLib
- base
- Baubles
- bdlib
- BetterBuildersWands
- Biomes O Plenty
- Bookshelf
- Botania
- BrandonsCore
- Buildcraft
- chickens
- Chisel
- ClayBucket
- CodeChickenLib
- CoFHCore
- CoFHWorld
- conarm
- ContentTweaker
- Cosmetic Armor Reworked
- Craft Tweaker
- CTM
- Cucumber
- Decicraft
- Draconic Evolution
- Enchanting Plus
- Ender Core
- Ender Storage
- Extra Utils 2
- Extreme Reactors
- Forestry
- Forgelin
- FTBLib
- FTB Utilities
- FTB Utilities Backup
- Furniture
- Gendustry
- Hatchery
- Hwyla
- Ice and Fire
- Immersive Engineering
- Immersive Petroleum
- Immersive Tech
- Industrial Craft 2
- Inventory Pets
- Inventory Tweaks
- Iron Backpacks
- Iron Chest
- JAOPCA
- Jei
- Jei Bees
- Jei Villagers
- Journeymap
- llibrary
- Logistic Pipes
- Mantle
- mcjtylib
- Mekanism
- More Chickens
- Mowzies Mobs
- Mystical Agriculture
- NEI
- omlib
- Open Computers
- Open Modular Turrets
- Pam's harverst craft
- PTRLib
- Quark
- Redstone Flux
- Reliquary
- rftools
- Roguelike Dungeons
- Rustic
- Super Sound Muffler
- TConstruct
- Thaumcraft
- Thaumcraft JEI
- Thermal Cultivation
- Thermal Dynamics
- Thermal Expansion
- Thermal Foundation
- Thermal Innovation
- Tiker Tool Leveling
- Trumpet Skeleton
- Twilight Forest
- Wawla
- Waystones
- Wolf Armor
- Wrap Up
- XNet
- Zero Core

**Comment by dusmartijngames** [comment]
hi mulukou. the mod quark prefents your server from booting up. try to use one of the following catfix jar files of quark https://mega.nz/#F!PQommYJa!DHzLp2mX850ydOrBmTqGiQ (comes from the home page of catserver)
