### ISSUE TITLE
Spigot Plugin citizens-2.0.24-SNAPSHOT not work

### ISSUE THREAD

**Issue by johnbli** [CatServer/CatServer#5]
[Mi, 20. Feb 2019 17:19:16 MEZ INFO] JohnMurdoc issued server command: /npc create JohnMurdoc
[Mi, 20. Feb 2019 17:19:16 MEZ WARN] java.lang.IllegalAccessError
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.citizensnpcs.nms.v1_12_R1.util.PlayerNavigation.<init>(PlayerNavigation.java:49)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:333)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.citizensnpcs.nms.v1_12_R1.entity.HumanController.createEntity(HumanController.java:81)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:209)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:422)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at java.lang.reflect.Method.invoke(Unknown Source)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.citizensnpcs.Citizens.onCommand(Citizens.java:238)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:700)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1591)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1436)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at java.util.concurrent.FutureTask.run(Unknown Source)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.minecraft.util.Util.func_181617_a(Util.java:50)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:843)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:780)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634)
[Mi, 20. Feb 2019 17:19:16 MEZ WARN]     at java.lang.Thread.run(Unknown Source)
[Mi, 20. Feb 2019 17:19:31 MEZ INFO] [MysqlPlayerDataBridge] Saving online players data...
[Mi, 20. Feb 2019 17:19:31 MEZ INFO] [MysqlPlayerDataBridge] Data save complete for 1 players in 125 ms.

**Comment by CatServer** [comment]
fix: https://mega.nz/#!CQxxQSII!isZQqsxQ7aa6R3PgFgHKrc2i1uD3arY7IsntxnH8TZk

**Comment by johnbli** [comment]
fix is not work

12:03:10
 CONSOLE:
[INFO] JohnMurdoc issued server command: /npc create test
12:03:10
 CONSOLE:
[INFO] npc
12:03:11
 CONSOLE:
thread/WARN]: java.lang.IllegalAccessError
12:03:11
 CONSOLE:
thread/WARN]: at net.citizensnpcs.nms.v1_12_R1.util.PlayerNavigation.<init>(PlayerNavigation.java:49)
12:03:11
 CONSOLE:
thread/WARN]: at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:333)
12:03:11
 CONSOLE:
thread/WARN]: at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
12:03:11
 CONSOLE:
thread/WARN]: at net.citizensnpcs.nms.v1_12_R1.entity.HumanController.createEntity(HumanController.java:52)
12:03:11
 CONSOLE:
thread/WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
12:03:11
 CONSOLE:
thread/WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:209)
12:03:11
 CONSOLE:
thread/WARN]: at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:423)
12:03:11
 CONSOLE:
thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:03:11
 CONSOLE:
thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
12:03:11
 CONSOLE:
thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
12:03:11
 CONSOLE:
thread/WARN]: at java.lang.reflect.Method.invoke(Unknown Source)
12:03:11
 CONSOLE:
thread/WARN]: at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
12:03:11
 CONSOLE:
thread/WARN]: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
12:03:11
 CONSOLE:
thread/WARN]: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
12:03:11
 CONSOLE:
thread/WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:238)
12:03:11
 CONSOLE:
thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
12:03:11
 CONSOLE:
thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
12:03:11
 CONSOLE:
thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:700)
12:03:11
 CONSOLE:
thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1591)
12:03:11
 CONSOLE:
thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1436)
12:03:11
 CONSOLE:
thread/WARN]: at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
12:03:11
 CONSOLE:
thread/WARN]: at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
12:03:11
 CONSOLE:
thread/WARN]: at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
12:03:11
 CONSOLE:
thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
12:03:11
 CONSOLE:
thread/WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
12:03:11
 CONSOLE:
thread/WARN]: at net.minecraft.util.Util.func_181617_a(Util.java:50)
12:03:11
 CONSOLE:
thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:843)
12:03:11
 CONSOLE:
thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
12:03:11
 CONSOLE:
thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:780)
12:03:11
 CONSOLE:
thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634)
12:03:11
 CONSOLE:
thread/WARN]: at java.lang.Thread.run(Unknown Source)

**Comment by CatServer** [comment]
Please try upgrade to git-5877863

**Comment by johnbli** [comment]
Not Work

19:25:40

JohnMurdoc issued server command: /npc create JohnMurdoc
npc

Server thread/ERROR
 
08.03.2019 19:25:40

19:25:40

Exception caught during firing event net.minecraftforge.event.entity.EntityJoinWorldEvent@6b6ea7c9:

Console
 
08.03.2019 19:25:40

19:25:40

java.lang.NullPointerException: null
at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:37) ~[ForgeEvents.class:1.12.2-5.5.3]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1076_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:187) [EventBus.class:?]
at net.minecraft.world.World.addEntity(World.java:1453) [amu.class:?]
at net.minecraft.world.WorldServer.addEntity(WorldServer.java:1339) [oo.class:?]
at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.addEntityToWorld(NMSImpl.java:233) [Citizens.jar:?]
at net.citizensnpcs.util.NMS.addEntityToWorld(NMS.java:42) [Citizens.jar:?]
at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:214) [Citizens.jar:?]
at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:423) [Citizens.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155) [Citizens.jar:?]
at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87) [Citizens.jar:?]
at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183) [Citizens.jar:?]
at net.citizensnpcs.Citizens.onCommand(Citizens.java:238) [Citizens.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:git-Spigot-dcd1643-e60fc34]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [SimpleCommandMap.class:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:702) [CraftServer.class:git-Spigot-dcd1643-e60fc34]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1591) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1436) [pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:843) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:780) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

Server thread/ERROR
 
08.03.2019 19:25:40

19:25:40

Index: 17 Listeners:
0: HIGHEST
1: ASM: net.minecraftforge.common.ForgeInternalHandler@44baf252 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
2: ASM: hellfirepvp.astralsorcery.common.util.BlockDropCaptureAssist@2d236202 onDrop(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
3: HIGH
4: ASM: hellfirepvp.astralsorcery.common.constellation.perk.attribute.type.AttributeCritChance@dc154bd7 onArrowCt(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
5: NORMAL
6: ASM: class crazypants.enderio.base.handler.darksteel.PlayerAOEAttributeHandler handleJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
7: ASM: class cam72cam.immersiverailroading.proxy.ServerProxy onEntityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
8: ASM: baubles.common.event.EventHandlerEntity@1d077b8e playerJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
9: ASM: com.rwtema.extrautils2.items.DemonicIngotHandler@87e4e44 onJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
10: ASM: com.rwtema.extrautils2.blocks.BlockCursedEarth$EventHandler@600383cf spawnInWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
11: ASM: hellfirepvp.astralsorcery.common.constellation.perk.attribute.type.AttributeArrowSpeed@b96d0033 onArrowFire(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
12: ASM: jds.bibliocraft.events.EventSpawn@3f617b4f onSpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
13: ASM: class com.enderio.core.common.handlers.XPBoostHandler handleArrowFire(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
14: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerEntity@5f428250 onSpawnDropCloud(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
15: ASM: li.cil.oc.common.EventHandler$@7cc7109c onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
16: ASM: blusunrize.immersiveengineering.common.EventHandler@41ec3747 onEntityJoiningWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
17: ASM: journeymap.server.events.ForgeEvents@72e30596 on(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
18: ASM: net.geforcemods.securitycraft.SCEventHandler@ca85d1e onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
19: ASM: com.rwtema.extrautils2.villagers.EntityAINinjaPoof$Handler@58900924 a(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
20: ASM: class com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim onJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
21: LOW
22: ASM: com.brandon3055.brandonscore.handlers.BCEventHandler@4081ad42 entityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
23: LOWEST
24: ASM: hellfirepvp.astralsorcery.common.constellation.perk.attribute.type.AttributeCritMultiplier@8bcd7c54 onArrowCt(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
25: ASM: oreexcavation.handlers.EventHandler@69764a08 onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V

Server thread/WARN
 
08.03.2019 19:25:40

19:25:40

java.lang.NullPointerException
at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:37)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1076_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:187)
at net.minecraft.world.World.addEntity(World.java:1453)
at net.minecraft.world.WorldServer.addEntity(WorldServer.java:1339)
at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.addEntityToWorld(NMSImpl.java:233)
at net.citizensnpcs.util.NMS.addEntityToWorld(NMS.java:42)
at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:214)
at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:423)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
at net.citizensnpcs.Citizens.onCommand(Citizens.java:238)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:702)
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1591)
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1436)
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at net.minecraft.util.Util.func_181617_a(Util.java:50)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:843)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:780)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634)
at java.lang.Thread.run(Unknown Source)

**Comment by CatServer** [comment]
Please remove the mod journeymap from your server
