### ISSUE TITLE
Concurrent Modification Exception Crash

### ISSUE THREAD

**Issue by Zilacon** [CatServer/CatServer#59]
This error likes to blame certain mods for it, even after removal it ends up just being a modless crash error of the same type. Removing reforged and  Foamfix results in the same crash just without the modded ASM handler line.

```
Description: Exception in server tick loop

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
    at java.util.ArrayList$Itr.next(ArrayList.java:859)
    at org.silvercatcher.reforged.ReforgedEvents.onWorldTick(ReforgedEvents.java:113)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_917_ReforgedEvents_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:187)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:918)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:778)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
    at java.lang.Thread.run(Thread.java:813)
```

**Comment by Luohuayu** [comment]
I can't download LagAssist, it's a paid plugin
These error seems to be the plugin's own problem

**Comment by Luohuayu** [comment]
Remove LagAssist plugin, the plugin asynchronously load chunk causing mod to crash!

**Comment by Luohuayu** [comment]
In crash file:
`RUNNABLE Craft Scheduler Thread - 182: [net.minecraft.entity.Entity.<init>(Entity.java:277)
net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:201)
net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:98)
net.minecraft.entity.EntityCreature.<init>(EntityCreature.java:22)
net.minecraft.entity.EntityAgeable.<init>(EntityAgeable.java:54)
net.minecraft.entity.passive.EntityAnimal.<init>(EntityAnimal.java:31)
com.animania.common.entities.amphibians.EntityAmphibian.<init>(EntityAmphibian.java:55)
com.animania.common.entities.amphibians.EntityAmphibian.<init>(EntityAmphibian.java:62)
com.animania.common.entities.amphibians.EntityFrogs.<init>(EntityFrogs.java:61)
sun.reflect.GeneratedConstructorAccessor260.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:306)
net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:292)
net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:67)
net.minecraft.entity.EntityList.func_188429_b(EntityList.java:208)
net.minecraft.entity.EntityList.func_75615_a(EntityList.java:215)
net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:607)
net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:534)
net.minecraftforge.common.ForgeChunkManager.loadChunkEntities(ForgeChunkManager.java:1028)
net.minecraftforge.common.ForgeChunkManager.fetchDormantChunk(ForgeChunkManager.java:1017)
net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:106)
net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:96)
net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:142)
org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:267)
org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:718)
org.bukkit.Location.getChunk(Location.java:82)
cx.sfy.LagAssist.stacker.StackMonitor.runMove(StackMonitor.java:76)
cx.sfy.LagAssist.stacker.StackMonitor.lambda$1(StackMonitor.java:57)
cx.sfy.LagAssist.stacker.StackMonitor$$Lambda$2631.00000000C0F7A380.run(Unknown Source)
org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:813)]`
