### ISSUE TITLE
LibsDisguises 插件无法正常运行。

### ISSUE THREAD

**Issue by MikuSnow** [CatServer/CatServer#6]
```
[15:20:00] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v9.5.1
[15:20:01] [Server thread/INFO]: [LibsDisguises] Discovered nms version: v1_12_R1
[15:20:02] [Server thread/WARN]: java.lang.NoSuchFieldException: worlds
[15:20:02] [Server thread/WARN]:        at java.lang.Class.getField(Unknown Source)
[15:20:02] [Server thread/WARN]:        at catserver.server.remapper.ReflectionMethods.getField(ReflectionMethods.java:30)
[15:20:02] [Server thread/WARN]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.init(DisguiseUtilities.java:870)
[15:20:02] [Server thread/WARN]:        at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:43)
[15:20:02] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:20:02] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327)
[15:20:02] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[15:20:02] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:433)
[15:20:02] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:382)
[15:20:02] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:476)
[15:20:02] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:431)
[15:20:02] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:388)
[15:20:02] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327)
[15:20:02] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600)
[15:20:02] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[15:20:03] [Server thread/WARN]: Error finding the FlagType for HORSE! Index 17 can't be found!
[15:20:03] [Server thread/WARN]: Value is 1xtile.air@0 (class net.minecraft.item.ItemStack) (class net.minecraft.entity.passive.EntityHorse) & HorseWatcher
[15:20:03] [Server thread/WARN]: Lib's Disguises will continue to load, but this will not work properly!
[15:20:03] [Server thread/INFO]: [LibsDisguises] Loaded custom disguise libraryaddict
[15:20:03] [Server thread/INFO]: [LibsDisguises] Loaded 1 custom disguise
```

**Comment by CatServer** [comment]
已发布修复版插件
