### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by Wr0ngPass** [CatServer/CatServer#60]
`20:44:04] [Server thread/INFO]: [Factions 2.14.0] === ENABLE START ===
[20:44:05] [Server thread/ERROR]: Error occurred while enabling Factions v2.14.0 (Is it up to date?)
java.lang.IllegalStateException: java.lang.ClassNotFoundException: Failed to remap class com.massivecraft.factions.integration.herochat.ChannelFactionsAllies
        at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:331) ~[?:?]
        at com.massivecraft.massivecore.util.ReflectionUtil.getPackageClasses(ReflectionUtil.java:481) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:446) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:416) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.getClassesActiveIntegrations(MassivePlugin.java:391) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:337) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateAuto(MassivePlugin.java:324) ~[?:?]
        at com.massivecraft.factions.Factions.onEnableInner(Factions.java:80) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [JavaPluginLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [SimplePluginManager.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:434) [CraftServer.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:383) [CraftServer.class:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:480) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:435) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:392) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:604) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.massivecraft.factions.integration.herochat.ChannelFactionsAllies
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:195) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at catserver.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:101) ~[ReflectionMethods.class:git-4894c2a-Community]
        at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
        ... 19 more
Caused by: java.lang.NoClassDefFoundError: com/massivecraft/factions/integration/herochat/ChannelFactionsAbstract
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at catserver.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:101) ~[ReflectionMethods.class:git-4894c2a-Community]
        at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
        ... 19 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.massivecraft.factions.integration.herochat.ChannelFactionsAbstract
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:195) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at catserver.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:101) ~[ReflectionMethods.class:git-4894c2a-Community]
        at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
        ... 19 more
Caused by: java.lang.NoClassDefFoundError: com/dthielke/herochat/Channel
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at catserver.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:101) ~[ReflectionMethods.class:git-4894c2a-Community]
        at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
        ... 19 more
Caused by: java.lang.ClassNotFoundException: com.dthielke.herochat.Channel
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:127) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at catserver.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:101) ~[ReflectionMethods.class:git-4894c2a-Community]
        at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
        ... 19 more`

**Comment by johncsuti** [comment]
Ask the plugin owner for help on this issue
