### ISSUE TITLE
 advancedRocketry server  crash 

### ISSUE THREAD

**Issue by heran983** [CatServer/CatServer#73]
[Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:915) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:472) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:778) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassCastException: zmaster587.advancedRocketry.world.util.WorldDummy cannot be cast to net.minecraft.world.WorldServer
        at org.bukkit.craftbukkit.v1_12_R1.CraftChunk.<init>(CraftChunk.java:32) ~[CraftChunk.class:git-CatServer-1.12.2-3c5e7d0]
        at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:131) ~[axw.class:?]
        at zmaster587.advancedRocketry.util.StorageChunk.<init>(StorageChunk.java:93) ~[StorageChunk.class:unspecified]
        at zmaster587.advancedRocketry.util.StorageChunk.copyWorldBB(StorageChunk.java:489) ~[StorageChunk.class:unspecified]
        at zmaster587.advancedRocketry.util.StorageChunk.cutWorldBB(StorageChunk.java:619) ~[StorageChunk.class:unspecified]
        at zmaster587.advancedRocketry.tile.TileRocketBuilder.assembleRocket(TileRocketBuilder.java:366) ~[TileRocketBuilder.class:unspecified]
        at zmaster587.advancedRocketry.tile.TileRocketBuilder.performFunction(TileRocketBuilder.java:197) ~[TileRocketBuilder.class:unspecified]
        at zmaster587.libVulpes.tile.TileEntityRFConsumer.update(TileEntityRFConsumer.java:123) ~[TileEntityRFConsumer.class:unspecified]
        at net.minecraft.world.World.redirect$tileEntityUpdate$zzj000(World.java:4473) ~[amu.class:?]
        at net.minecraft.world.World.updateEntities(World.java:2107) ~[amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:857) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:908) ~[MinecraftServer.class:?]

**Comment by Tenoen** [comment]
I got around the issue by adding the VanillaFix mod to the server prior to installing Advanced Rocketry. No idea why it works, but it does!
